datasets:
    sequence-size: 2 # must be >= 2
    kitti:
      root-path: "/media/ajava/Data/Datasets/KITTI/"
      image-width: 1800
      image-height: 64
      crop-factors: [0, 4] # top, left
      fov-up: 3.
      fov-down: -25.
      max-depth: 80.
      min-depth: 1.
      inverse-depth: true
      train:
        2011-10-03: [27, 42, 34]
        2011-09-30: [16, 18, 20, 27]
      test:
        # 2011-09-30: [33, 34]
        2011-10-03: [42]
      validation:
        2011-09-26: [32, 46]

      # channesl: x, y, z, range(x,y,z), remissions)
      mean: [-0.05815, 0.4165, -0.8585, 0.1029, 0.2164]
      std: [10.0366, 7.4936, 0.8761, 0.0857, 0.1740]

      #mean: [-0.0581, 0.4165, -0.8585, 8.2594, 0.2164]
      #std: [10.0366, 7.4936, 0.8761, 9.5056, 0.1740]

arch:
  name: "deeplio3"
  dropout: 0.5

  feature-net:
    name: "pointseg"
    pretrained: False
    model-path: "resources/checkpoint_30_20200504_161441.tar"
    dropout: 0.25
    classes: ['unknown', 'car', 'pedestrian', 'cyclist']

losses:
  active: 'hwsloss'
  hwsloss:
    params:
      learn: true
      sx: 0.
      sq: -2.5
  lwsloss:
    prams:
      beta: 1125.

current-dataset: 'kitti'
channels: [3, 4] # channesl: x=0, y=1, z=2, range(x,y,z)=3, remissions=4
optimizer: 'sgd'




