datasets:
  sequence-size: 2 # must be >= 1
  combinations: [[0, 2], [1, 2]]
  kitti:
    root-path-sync: "datasets/KITTI/sync"
    root-path-unsync: "datasets/KITTI/extract"
    image-width: 720 # 1800
    image-height: 64
    crop-factors: [0, 16] # [0, 4] # top, left
    fov-up: 3.
    fov-down: -25.
    max-depth: 80.
    min-depth: 1.
    inverse-depth: true
    train:
      2011-10-03: [27, 42, 34]
      2011-09-30: [16, 18, 20, 27, 28]
    test:
      2011-09-30: [33, 34]
    validation:
      2011-09-26: [23, 39]

    # channesl: x, y, z, range(x,y,z), remissions)
    mean-image: [-0.05815, 0.4165, -0.8585, 0.1029, 0.2164]
    std-image: [10.0366, 7.4936, 0.8761, 0.0857, 0.1740]
    mean-imu: [-0.0635, 0.186, 9.7966, 0., 0.0005, 0.0082]
    std-imu: [0.8525, 0.9516, 0.3401, 0.0198, 0.02204, 0.1383]

    #mean: [-0.0581, 0.4165, -0.8585, 8.2594, 0.2164]
    #std: [10.0366, 7.4936, 0.8761, 9.5056, 0.1740]

### DeepLIO Networks ##############################

# Lidar and IMU (DeepLIO) Neuronal Network
deeplio:
  dropout: 0.25
  pretrained: false
  model-path: ""
  lidar-feat-net:
    name: "lidar-feat-simple-1" # [simple0, simple1, pointseg]
    pretrained: false
    model-path: ""
  imu-feat-net:
    name: "imu-feat-rnn"
    pretrained: false
    model-path: ""
  odom-feat-net:
    name: "odom-feat-rnn" # [fc, rnn]
    pretrained: false
    model-path: ""
  fusion-net: "fusion-layer"

# Lidar Neuronal Network
deeplo:
  dropout: 0.25
  pretrained: false
  model-path: ""
  lidar-feat-net:
    name: "lidar-feat-simple-1" # [simple0, simple1, pointseg]
    pretrained: false
    model-path: ""
  odom-feat-net:
    name: "odom-feat-rnn" # [fc, rnn]
    pretrained: false
    model-path: ""

# IMU Neuronal Network
deepio:
  dropout: 0.
  pretrained: false
  model-path: ""
  imu-feat-net:
    name: "imu-feat-rnn"  # [fc, rnn]
    pretrained: false
    model-path: ""

### Lidar Feature Netowrks ###########################
# feature network simple0 with conv layers
lidar-feat-simple-0:
  dropout: 0.
  fusion: cat # [cat, sub]

# feature network simple0 with bypassed conv layers
lidar-feat-simple-1:
  dropout: 0.
  fusion: cat # [cat, sub]
  bypass: true

# feature network pointseg
lidar-feat-pointseg:  # pointseg feature
  dropout: 0.
  classes: ['unknown', 'object']
  bypass: true
  fusion: cat # [cat, sub]
  part: "encoder" # [encoder, encoder+decoder]

### Odometry Feature Netowrks ###########################
# odometry feature network with fully connected layers
odom-feat-fc:
  size: [512]
  fusion: cat # [cat, sub]
  dropout: 0.

# odometry feature network with rnn-layers
odom-feat-rnn:
  type: "lstm"
  hidden-size: 512
  num-layers: 2
  bidirectional: false
  dropout: 0.

### IMU Feature Netowrks ###########################
# IMU Feature Netowrks
imu-feat-fc:  # FC
  input-size: 6  # !fixed! do not chanage
  hidden-size: [256, 256]
  dropout: 0.

imu-feat-rnn: # RNN
  type: "lstm"
  input-size: 6  # !fixed! do not chanage
  hidden-size: 256
  num-layers: 2
  bidirectional: true
  dropout: 0.

### Fusion-Layer for DeepLIO Net ###########################
fusion-layer:
  type: "cat" # [cat, soft-fusion]

### Loss Configurations ###########################
losses:
  active: 'lwsloss'
  hwsloss:
    params:
      learn: true
      sx: 0.
      sq: -2.5
  lwsloss:
    params:
      beta: 1125.
  geoloss:
    params:

arch: "deepio"  # [deepio, deeplo, deeplio]
current-dataset: 'kitti'
channels: [3, 4] # channesl: x=0, y=1, z=2, range(x,y,z)=3, remissions=4
optimizer: 'adam'






