datasets:
    kitti:
      root-path: "/media/ajava/Data/Datasets/KITTI/raw_unsync"
      image-width: 1800
      image-height: 64
      fov-up: 3.
      fov-down: -25.
      sequence-size: 3
      max-depth: 80.
      min-depth: 2.
      inverse-depth: true
      train:
          "2011_10_03": ['27', '42', '34']
          "2011_09_30": ['16', '18', '20', '27']
      test:
          "2011_09_30": ['33', '34']
      val:
          "2011_09_30": ['28']

      mean: [0.2163, 0.6695] # channesl: x=0, y=1, z=2, remissions=3, range(x,y,z)=4, depth(x,y)=5
      std: [0.174, 0.3948] # channesl: x=0, y=1, z=2, remissions=3, range(x,y,z)=4, depth(x,y)=5

batch-size: 3
epoch: 2

current-dataset: 'kitti'
channels: [3, 4] # channesl: x=0, y=1, z=2, remissions=3, range(x,y,z)=4, depth(x,y)=5
