datasets:
    kitti:
      root-path: "/media/ajava/Data/Datasets/KITTI/raw_unsync"
      image-width: 1800
      image-height: 64
      fov-up: 3.
      fov-down: -25.
      sequence-size: 2
      train:
          "2011_10_03": ['27', '34', '42']
          "2011_09_30": ['28']
      test:
          "2011_09_30": [1, 5]
          "2011_10_05": [10, 8, 45]
      val:
        2011_09_10: [3]

      mean: [0.25, 8.13603493] # channesl: x=0, y=1, z=2, remissions=3, range(x,y,z)=4, depth(x,y)=5
      std: [0.17477078, 9.49465492] # channesl: x=0, y=1, z=2, remissions=3, range(x,y,z)=4, depth(x,y)=5

channels: [3, 4] # channesl: x=0, y=1, z=2, remissions=3, range(x,y,z)=4, depth(x,y)=5




