datasets:
  sequence-size: 2 # must be >= 2
  combinations: [[0, 2], [1, 2]]
  kitti:
    root-path-sync: "datasets/KITTI/sync"
    root-path-unsync: "datasets/KITTI/extract"
    image-width: 1800
    image-height: 64
    crop-factors: [0, 4] # top, left
    fov-up: 3.
    fov-down: -25.
    max-depth: 80.
    min-depth: 1.
    inverse-depth: true
    train:
      #2011-10-03: [27, 42, 34]
      2011-09-30: [16] # [16, 18, 20, 27, 28]
    test:
      # 2011-09-30: [33, 34]
      2011-10-03: [27]
    validation:
      2011-09-26: [23, 39]

    # channesl: x, y, z, range(x,y,z), remissions)
    mean-image: [-0.05815, 0.4165, -0.8585, 0.1029, 0.2164]
    std-image: [10.0366, 7.4936, 0.8761, 0.0857, 0.1740]
    mean-imu: [-0.0635, 0.186, 9.7966, 0., 0.0005, 0.0082]
    std-imu: [0.8525, 0.9516, 0.3401, 0.0198, 0.02204, 0.1383]

    #mean: [-0.0581, 0.4165, -0.8585, 8.2594, 0.2164]
    #std: [10.0366, 7.4936, 0.8761, 9.5056, 0.1740]

### DNN Models

# Lidar and IMU (DeepLIO) Neuronal Network
deeplio:
  name: "deeplio1" # [deeplioS0, deeplioS1, DeepLIO0, DeepLIO1]
  dropout: 0.25
  fusion: "cat"
  odom-feat-net: "rnn"
  rnn:
    type: "lstm"
    hidden-size: 512
    num-layers: 2
    bidirectional: false
  fc:
    size: [512]

### DeepLO Configurations ###########################
deeplo:
  #name: "deeplo" # [deeplioS0, deeplioS1, DeepLIO0, DeepLIO1]
  dropout: 0.25
  pretrained: false
  model-path: ""
  feature-net:
    name: "deeplo-feat-pointseg" # [simple0, simple1]
    pretrained: false
    model-path: ""
  odom-feat-net:
    name: "deeplo-odom-feat-fc" # [simple0, simple1]
    pretrained: false
    model-path: ""

# odometry feature network with rnn-layers
deeplo-odom-feat-rnn:
  type: "lstm"
  hidden-size: 512
  num-layers: 2
  bidirectional: false

# odometry feature network with fully connected layers
deeplo-odom-feat-fc:
  size: [512]
  fusion: cat # [cat, sub]

# feature network simple0 with conv layers
deeplo-feat-simple-0:
  dropout: 0.
  fusion: cat # [cat, sub]

# feature network simple0 with bypassed conv layers
deeplo-feat-simple-1:
  dropout: 0.
  fusion: cat # [cat, sub]
  bypass: true

# feature network pointseg
deeplo-feat-pointseg:  # pointseg feature
  dropout: 0.
  classes: ['unknown', 'object']
  bypass: true
  fusion: cat # [cat, sub]
  part: "encoder" # [encoder, encoder+decoder]

### DeepIO Configurations ###########################
deepio:
  dropout: 0.25
  pretrained: false
  model-path: "outputs/train_deepio_20200612_104605/cpkt_DeepIO_DeepIOFeat1.tar"
  feature-net:
    name: "deepio1"
    pretrained: true
    model-path: "outputs/train_deepio_20200612_104605/cpkt_DeepIOFeat1.tar"

# IMU Feature Netowrks
deepio0:  # FC
  input-size: 6  # !fixed! do not chanage
  hidden-size: [256, 256]

deepio1: # RNN
  type: "lstm"
  input-size: 6  # !fixed! do not chanage
  hidden-size: 256
  num-layers: 2
  bidirectional: true

### Loss Configurations ###########################
losses:
  active: 'lwsloss'
  hwsloss:
    params:
      learn: true
      sx: 0.
      sq: -2.5
  lwsloss:
    params:
      beta: 1125.
  geoloss:
    params:

arch: "deeplo"  # [deepio, deeplo, deeplio]
current-dataset: 'kitti'
channels: [3, 4] # channesl: x=0, y=1, z=2, range(x,y,z)=3, remissions=4
optimizer: 'adam'






